== Memory-mapped register interface

The IOMMU provides a memory-mapped programming interface. The memory-mapped 
registers of each IOMMU are located within a naturally aligned 4-KiB region 
(a page) of physical address space. 

The IOMMU behavior for register accesses where the address is not aligned to 
the size of the access or if the access spans multiple registers is undefined.

The reset default value of register fields is 0 unless explicitly noted 
otherwise in the register definition.

Register fields are assigned one of the attributes described in following 
table.

.Register and Register bit-field types
[width=90%]
[%header, cols="^3, 10"]
|===
^|Attribute    ^|                      Description
| RW            | Read-Write - Register bits are read-write and are permitted 
                  to be either Set or Cleared by software to the desired state.

                  If the optional feature that is associated with the bits is 
                  not implemented, the bits are permitted to be hardwired to
                  Zero.
| RO            | Read-only - Register bits are read-only and cannot be altered
                  by software. Where explicitly defined, these bits are used
                  to reflect changing hardware state, and as a result bit 
                  values can be observed to change at run time.

                  If the optional feature that would Set the bits is not 
                  implemented, the bits must be hardwired to Zero
| RW1C          | Write-1-to-clear status - Register bits indicate status when 
                  read. A Set bit indicates a status event which is Cleared by
                  writing a 1b. Writing a 0b to RW1C bits has no effect.

                  If the optional feature that would Set the bit is not 
                  implemented, the bit must be read-only and hardwired to Zero
| WPRI          | Reserved Writes Preserve Values, Reads Ignore Values. See
                  RISC-V privileged specification for a detailed definition.
| WARL          | Write Any Values, Reads Legal Values. See RISC-V privileged 
                  specification for a detailed definition.
|===


=== Register layout

.IOMMU Memory-mapped register layout
[width=90%]
[%header, cols="^3,6,^3, 18"]
|===
|Offset|Name            |Size|Description
|0     |`capabilities`  |8   |<<CAP, Capabilities supported by the IOMMU>>
|8     |`fctrl`         |4   |<<FCTRL, Features control>>
|12    |_custom_        |4   |_For custom use_
|16    |`ddtp`          |8   |<<DDTP, Device directory table pointer>>
|24    |`cqb`           |8   |<<CQB, Command-queue base>>
|32    |`cqh`           |4   |<<CQH, Command-queue head>>
|36    |`cqt`           |4   |<<CQT, Command-queue tail>>
|40    |`fqb`           |8   |<<FQB, Fault-queue base>>
|48    |`fqh`           |4   |<<FQH, Fault-queue head>>
|52    |`fqt`           |4   |<<FQT, Fault-queue tail>>
|56    |`pqb`           |8   |<<PQB, Page-request-queue base>>
|64    |`pqh`           |4   |<<PQH, Page-request-queue head>>
|68    |`pqt`           |4   |<<PQT, Page-request-queue tail>>
|72    |`cqcsr`         |4   |<<CSR, Command-queue control and status register>>
|76    |`fqcsr`         |4   |<<FQCSR, Fault-queue control and status register>>
|80    |`pqcsr`         |4   |<<PQCSR, Page-request-queue control 
                                     and status register>>
|84    |`ipsr`          |4   |<<IPSR, Interrupt pending status register>>
|88    |`iocntovf`      |4   |<<OVF, Performance-monitoring counter 
                                     overflow status>>
|92    |`iocntinh`      |4   |<<INH, Performance-monitoring counter inhibits>>
|96    |`iohpmcycles`   |8   |<<CYC, Performance-monitoring cycles counter>>
|104   |`iohpmctr1 - 31`|248 |<<CTR, Performance-monitoring event counters>>
|352   |`iohpmevt1 - 31`|248 |<<EVT, Performance-monitoring event selector>>
//|600   |`iocntconf`     |4   |<<CONF, Counters reserved for confidential mode usage>>
//|604   |Reserved        |78  |Reserved for future use (`WPRI`)
|600   |Reserved        |82  |Reserved for future use (`WPRI`)
|682   |_custom_        |78  |_Reserved for custom use (`WARL`)_
|760   |`icvec`         |4   |<<ICVEC, Interrupt cause to vector register>>
|768   |`msi_cfg_tbl`   |256 |<<MSI, MSI Configuration Table>>
|1024  |Reserved        |3072|Reserved for future use (`WPRI`)
|===


[[CAP]]
=== IOMMU capabilities (`capabilities`)

The `capabilities` register is a read-only register reporting features supported
by the IOMMU. Each field if not clear indicates presence of that feature in 
the IOMMU. At reset, the register shall contain the IOMMU supported features.

.capabilities register fields
[wavedrom, , ]
....
{reg: [
  {bits: 8, name: 'version'},
  {bits: 1, name: 'Sv32'},
  {bits: 1, name: 'Sv39'},
  {bits: 1, name: 'Sv48'},
  {bits: 1, name: 'Sv57'},
  {bits: 2, name: 'reserved'},
  {bits: 1, name: 'Svnapot'},
  {bits: 1, name: 'Svpbmt'},
  {bits: 1, name: 'Sv32x4'},
  {bits: 1, name: 'Sv39x4'},
  {bits: 1, name: 'Sv48x4'},
  {bits: 1, name: 'Sv57x4'},
  {bits: 2, name: 'reserved'},
  {bits: 1, name: 'MSI_FLAT'},
  {bits: 1, name: 'MSI_MRIF'},
  {bits: 1, name: 'AMO'},
  {bits: 1, name: 'ATS'},
  {bits: 1, name: 'T2GPA'},
  {bits: 1, name: 'END'},
  {bits: 2, name: 'IGS'},
  {bits: 1, name: 'PMON'},
  {bits: 1, name: 'reserved'},
  {bits: 6, name: 'PAS'},
  {bits: 10, name: 'reserved'},
  {bits: 16, name: 'custom'},
], config:{lanes: 8, hspace:1024}}
....

[width=100%]
[%header, cols="1,2,1,5"]
|===
|Bits  |Field      |Attribute | Description
|7:0   |`version`  |RO        | The `version` field holds the version of the 
                                specification implemented by the IOMMU. The low
                                nibble is used to hold the minor version of the
                                specification and the upper nibble is used to 
                                hold the major version of the specification. 
                                For example, an implementation that supports 
                                version 1.0 of the specification reports 0x10.
|8     |`Sv32`     |RO        | Page-based 32-bit virtual addressing is supported
|9     |`Sv39`     |RO        | Page-based 39-bit virtual addressing is supported
|10    |`Sv48`     |RO        | Page-based 48-bit virtual addressing is supported +
                                When `Sv48` field is set, `Sv39` field must be set.
|11    |`Sv57`     |RO        | Page-based 57-bit virtual addressing is supported +
                                When `Sv57` field is set, `Sv48` field must be set.
|13:12 | reserved  |RO        | Reserved for standard use.
|14    |`Svnapot`  |RO        | NAPOT translation contiguity.
|15    |`Svpbmt`   |RO        | Page-based memory types.
|16    |`Sv32x4`   |RO        | Page-based 34-bit virtual addressing for G-stage
                                translation is supported.
|17    |`Sv39x4`   |RO        | Page-based 41-bit virtual addressing for G-stage
                                translation is supported.
|18    |`Sv48x4`   |RO        | Page-based 50-bit virtual addressing for G-stage
                                translation is supported.
|19    |`Sv57x4`   |RO        | Page-based 59-bit virtual addressing for G-stage
                                translation is supported.
|21:20 | reserved  |RO        | Reserved for standard use.
|22    |`MSI_FLAT` |RO        | MSI address translation using Write-through 
                                mode MSI PTE is supported.
|23    |`MSI_MRIF` |RO        | MSI address translation using MRIF mode MSI PTE
                                is supported.
|24    |`AMO`      |RO        | Atomic updates to MRIF and PTE accessed (A) 
                                and dirty (D) bit is supported.
|25    |`ATS`      |RO        | PCIe Address Translation Services (ATS) and 
                                page-request interface (PRI) is supported.
|26    |`T2GPA`    |RO        | Returning guest-physical-address in ATS 
                                translation completions is supported.
|27    |`END`      |RO        | When 0, IOMMU supports one endianness (either little
                                or big). When 1, IOMMU supports both endianness.
                                The endianness is defined in `fctrl` register.
|29:28 |`IGS`      |RO       a| IOMMU interrupt generation support.

[%header, cols="^1,1,3"]
!===
                                !Value  !Name      ! Description
                                !0      ! `MSI`    ! IOMMU supports only MSI 
                                                     generation.
                                !1      ! `WIS`    ! IOMMU supports only wire
                                                     interrupt generation.
                                !2      ! `BOTH`   ! IOMMU supports both MSI 
                                                     and wire interrupt generation.
                                                     The interrupt generation method
                                                     must be defined in `fctrl`
                                                     register.
                                !3      ! 0        ! Reserved for standard use
!===

|30    |`PMON`     |RO        | IOMMU implements a performance-monitoring unit
|31    |`RAS`      |RO        | IOMMU implements the RISC-V RAS Registers
|37:32 |`PAS`      |RO        | Physical Address Size (value between 32 and 56)
|47:38 | reserved  |RO        | Reserved for standard use
|63:48 |_custom_   |RO        | _Reserved for custom use_
|===

[NOTE]
====
Hypervisor may provide an SW emulated IOMMU to allow the guest to manage 
the VS-stage page tables for fine grained control on memory accessed by guest 
controlled devices. 

A hypervisor that provides such an emulated IOMMU to the guest may retain 
control of the G-stage page tables and clear the `SvNx4` fields of the 
emulated `capabilities` register.

A hypervisor that provides such an emulated IOMMU to the guest may retain 
control of the MSI page tables used to direct MSI to guest interrupt files in 
an IMSIC or to a memory-resident-interrupt-file and clear the `MSI_FLAT` and 
`MSI_MRIF` fields of the emulated `capabilities` register.
====

[[FCTRL]]
=== Features-control register (`fctrl`)

This register must be readable in any implementation. An implementation may 
allow one or more fields in the register to be writable to support enabling
or disabling the feature controlled by that field.

If software enables or disables a feature when the IOMMU is not OFF 
(i.e. `ddtp.iommu_mode == Off`) then the IOMMU behavior is `UNSPECIFIED`.

.Features-control register fields
[wavedrom, , ]
....
{reg: [
  {bits: 1, name: 'END'},
  {bits: 1, name: 'WIS'},
  {bits: 14,  name: 'reserved'},
  {bits: 16,  name: 'custom'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,2,^1,5"]
|===
|Bits  |Field      |Attribute | Description
|0     |`END`      |WARL      | When 0, IOMMU accesses to memory resident data 
                                structures (e.g. DDT, PDT, in-memory queues, 
                                S/VS and G stage page tables) are performed as 
                                little-endian accesses and when 1 as 
                                big-endian accesses.
|1     |`WIS`      |WARL      | When 1, IOMMU interrupts are signaled as 
                                wired-interrupts.
|15:2  |`WPRI`     |WPRI      | Reserved for standard use
|31:16 |_custom_   |          | _These bits are reserved for custom use._
|===

[[DDTP]]
=== Device-directory-table pointer (`ddtp`)
.Device-directory-table pointer register fields
[wavedrom, , ]
....
{reg: [
  {bits: 44, name: 'PPN'},
  {bits: 15, name: 'reserved'},
  {bits: 1,  name: 'busy'},
  {bits: 4,  name: 'iommu_mode'},
], config:{lanes: 4, hspace:1024}}
....

[width=100%]
[%header, cols="^1,2,^1,5"]
|===
|Bits  |Field      |Attribute | Description
|43:0  |`PPN`      |WARL      | Holds the `PPN` of the root page of the 
                                device-directory-table.
|58:44 |`WPRI`     |WPRI      | Reserved for standard use
|59    |`busy`     |RW        | A write to `ddtp` may require the IOMMU to 
                                perform many operations that may not occur 
                                synchronously to the write. When a write is 
                                observed by the `ddtp`, the `busy` bit is set 
                                to 1. When the `busy` bit is 1, behavior of 
                                additional writes to the `ddtp` is 
                                implementation defined. Some implementations 
                                may ignore the second write and others may 
                                perform the actions determined by the second 
                                write. Software must verify that the `busy` 
                                bit is 0 before writing to the `ddtp`.

                                If the `busy` bit reads 0 then the IOMMU has 
                                completed the operations associated with the 
                                previous write to `ddtp`.

                                An IOMMU that can complete these operations 
                                synchronously may hard-wire this bit to 0.
|59    |`iommu_mode` |RW     a| The IOMMU may be configured to be in following
                                modes:

[%header, cols="^1,1,3"]
!===
                                !Value  !Name      ! Description
                                !0      ! `Off`    ! No inbound memory 
                                                     transactions are allowed 
                                                     by the IOMMU.
                                !1      ! `Bare`   ! No translation or 
                                                     protection. All inbound 
                                                     memory accesses are passed
                                                     through.
                                !2      ! `1LVL`   ! One-level 
                                                     device-directory-table
                                !3      ! `2LVL`   ! Two-level 
                                                     device-directory-table
                                !4      ! `3LVL`   ! Three-level 
                                                     device-directory-table
!===
|===

The device-context is 64-bytes in size if `capabilities.MSI_FLAT` is 1 else it is 
32-bytes.

When the `iommu_mode` is `Bare` or `Off`, the `PPN` field is don't-care. When 
in `Bare` mode only Untranslated requests are allowed. Translated requests, 
Translation request, and message transactions are unsupported.

All IOMMU must support `Off` and `Bare` mode. An IOMMU is allowed to support a 
subset of directory-table levels and device-context widths. At a minimum one 
of the modes must be supported.

When the `iommu_mode` field value is changed the IOMMU guarantees that 
in-flight transactions from devices connected to the IOMMU will be processed 
with the configurations applicable to the old value of the `iommu_mode` field 
and that all transactions and previous requests from devices that have already 
been processed by the IOMMU be committed to a global ordering point such that 
they can be observed by all RISC-V hart, devices, and IOMMUs in the platform.

[NOTE]
====
The reset default for the `iommu_mode` is recommended to be `Off`.
====

[[CQB]]
=== Command-queue base (`cqb`)

This 64-bits register (RW) holds the PPN of the root page of the command-queue
and number of entries in the queue. Each command is 16 bytes.

.Command-queue base register fields
[wavedrom, , ]
....
{reg: [
  {bits:  5, name: 'LOG2SZ-1'},
  {bits: 44, name: 'PPN'},
  {bits: 15, name: 'WPRI'},
], config:{lanes: 2, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits  |Field      |Attribute | Description
|4:0   |`LOG2SZ-1` |WARL     a| The `LOG2SZ-1` field holds the number of 
                                entries in command-queue as a log to base 2 
                                minus 1. 
                                A value of 0 indicates a queue of 2 entries.
                                Each IOMMU command is 16-bytes. 
                                If the command-queue has 256 or fewer entries 
                                then the base address of the queue is always 
                                aligned to 4-KiB. If the command-queue has more
                                than 256 entries then the command-queue 
                                base address must be naturally aligned to 
                                `2^LOG2SZ^ x 16`.
|48:5  |`PPN`      |WARL      | Holds the `PPN` of the root page of the 
                                in-memory command-queue used by software to 
                                queue commands to the IOMMU. 
|63:49 |`WPRI`     |WPRI      | Reserved for standard use
|===

[[CQH]]
=== Command-queue head (`cqh`)

This 32-bits register (RO) holds the index into the command-queue where 
the IOMMU will fetch the next command.

.Command-queue head register fields
[wavedrom, , ]
....
{reg: [
  {bits: 32, name: 'index'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits |Field   |Attribute | Description
|31:0 |`index` |RO        | Holds the `index` into the command-queue from where
                            the next command will be fetched next by the IOMMU.
|===

[[CQT]]
=== Command-queue tail (`cqt`)

This 32-bits register (RW) holds the index into the command-queue where 
the software queues the next command for the IOMMU.

.Command-queue tail register fields
[wavedrom, , ]
....
{reg: [
  {bits: 32, name: 'index'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits |Field   |Attribute | Description
|31:0 |`index` |WARL      | Holds the `index` into the command-queue where 
                            software queues the next command for IOMMU.  Only 
                            `LOG2SZ:0` bits are writable when the queue is 
                            in enabled state (i.e., `cqsr.cqon == 1`).
|===

[[FQB]]
=== Fault queue base (`fqb`)

This 64-bits register (RW) holds the PPN of the root page of the fault-queue
and number of entries in the queue. Each fault record is 32 bytes.

.Fault queue base register fields

[wavedrom, , ]
....
{reg: [
  {bits: 5, name: 'LOG2SZ-1'},
  {bits: 44, name: 'PPN'},
  {bits: 15, name: 'WPRI'},
], config:{lanes: 2, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits  |Field     |Attribute | Description
|4:0   |`LOG2SZ-1`|WARL     a| The `LOG2SZ-1` field holds the number of 
                               entries in fault-queue as a log-to-base-2 
                               minus 1. A value of 0 indicates a queue of 2 
                               entries. Each fault record is 32-bytes. 
                               If the fault-queue has 128 or fewer entries then 
                               the base address of the queue is always aligned 
                               to 4-KiB. If the fault-queue has more than 128 
                               entries then the fault-queue base address must 
                               be naturally aligned to `2^LOG2SZ^ x 32`.
|48:5  |`PPN`     |WARL      | Holds the `PPN` of the root page of the 
                               in-memory fault-queue used by IOMMU to queue 
                               fault record.
|63:49 |`WPRI`   |WPRI       | Reserved for standard use
|===

[[FQH]]
=== Fault queue head (`fqh`)

This 32-bits register (RW) holds the index into fault-queue where the
software will fetch the next fault record.

.Fault queue head register fields

[wavedrom, , ]
....
{reg: [
  {bits: 32, name: 'index'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits |Field   |Attribute |Description
|31:0 |`index` |WARL      | Holds the `index` into the fault-queue from which 
                            software reads the next fault record.  Only 
                            `LOG2SZ:0` bits are writable when the queue is 
                            in enabled state (i.e., `fqsr.fqon == 1`).
|===

[[FQT]]
=== Fault queue tail (`fqt`)

This 32-bits register (RO) holds the index into the fault-queue where the
IOMMU queues the next fault record.

.Fault queue tail register fields

[wavedrom, , ]
....
{reg: [
  {bits: 32, name: 'index'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits |Field   |Attribute | Description
|31:0 |`index` |RO        | Holds the `index` into the fault-queue where IOMMU 
                            writes the next fault record.
|===

[[PQB]]
=== Page-request-queue base (`pqb`)

This 64-bits register (RW) holds the PPN of the root page of the 
page-request-queue and number of entries in the queue. Each page-request
message is 16 bytes.

.Page-Request-queue base register fields

[wavedrom, , ]
....
{reg: [
  {bits: 5, name: 'LOG2SZ-1'},
  {bits: 44, name: 'PPN'},
  {bits: 15, name: 'WPRI'},
], config:{lanes: 2, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits  |Field     |Attribute | Description
|4:0   |`LOG2SZ-1`|WARL      | The `LOG2SZ-1` field holds the number of entries 
                               in page-request-queue as a log-to-base-2 minus 1.
                               A value of 0 indicates a queue of 2 entries. 
                               Each page-request is 16-bytes. If the 
                               page-request-queue has 256 or fewer entries 
                               then the base address of the queue is always 
                               aligned to 4-KiB.
                               If the page-request-queue has more than 256 
                               entries then the page-request-queue base address
                               must be naturally aligned to `2^LOG2SZ^ x 16`.
|48:5  |`PPN`     |WARL      | Holds the `PPN` of the root page of the 
                               in-memory page-request-queue used by IOMMU to 
                               queue "Page Request" messages.
|63:49 |`WPRI`    |WPRI      | Reserved for standard use
|===

[[PQH]]
=== Page-request-queue head (`pqh`)

This 32-bits register (RW) holds the index into the page-request-queue where
software will fetch the next page-request.

.Page-request-queue head register fields

[wavedrom, , ]
....
{reg: [
  {bits: 32, name: 'index'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits |Field   |Attribute | Description
|31:0 |`index` |WARL      | Holds the `index` into the page-request-queue from 
                            which software reads the next "Page Request" message.
                            Only `LOG2SZ:0` bits are writable when the queue is 
                            in enabled state (i.e., `pqsr.pqon == 1`).
|===

[[PQT]]
=== Page-request-queue tail (`pqt`)

This 32-bits register (RO) holds the index into the page-request-queue 
where the IOMMU writes the next page-request.

.Page-request-queue tail register fields

[wavedrom, , ]
....
{reg: [
  {bits: 32, name: 'index'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits |Field   |Attribute | Description
|31:0 |`index` |RO        | Holds the `index` into the page-request-queue 
                            where IOMMU writes the next "Page Request" message.
|===

[[CSR]]
=== Command-queue CSR (`cqcsr`)

This 32-bits register (RW) is used to control the operations and report the
status of the command-queue.

.Command-queue CSR register fields
[wavedrom, , ]
....
{reg: [
  {bits: 1, name: 'cqen'},
  {bits: 1, name: 'cie'},
  {bits: 6, name: 'WPRI'},
  {bits: 1, name: 'cqmf'},
  {bits: 1, name: 'cmd_to'},
  {bits: 1, name: 'cmd_ill'},
  {bits: 1, name: 'fence_w_ip'},
  {bits: 4, name: 'WPRI'},
  {bits: 1, name: 'cqon'},
  {bits: 1, name: 'busy'},
  {bits: 10, name: 'WPRI'},
  {bits: 4, name: 'Custom use'},
], config:{lanes: 4, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits |Field   |Attribute | Description
|0    |`cqen`  |RW        | The command-queue-enable bit enables the command-
                            queue when set to 1. Changing `cqen` from 0 to 1
                            sets the `cqh` and `cqt` to 0. The command-queue 
                            may take some time to be active following setting 
                            the `cqen` to 1. When the command queue is active,
                            the `cqon` bit reads 1.

                            When `cqen` is changed from 1 to 0, the command 
                            queue may stay active till the commands already 
                            fetched from the command-queue are being processed 
                            and/or there are outstanding implicit loads from 
                            the command-queue.  When the command-queue turns 
                            off, the `cqon` bit reads 0, `cqh` is set to 0, 
                            `cqt` is set to 0 and the `cqcsr` bits `cmd_ill`, 
                            `cmd_to`, `cqmf`, `fence_w_ip` are set to 0.

                            When the `cqon` bit reads 0, the IOMMU guarantees 
                            that no implicit memory accesses to the command 
                            queue are in-flight and the command-queue will not 
                            generate new implicit loads to the queue memory. 
|1    |`cie`   |RW        | Command-queue-interrupt-enable bit enables 
                            generation of interrupts from command-queue when 
                            set to 1.
|7:2  |`WPRI`  |WPRI      | Reserved for standard use
|8    |`cqmf`  |RW1C      | If command-queue access leads to a memory fault then
                            the command-queue-memory-fault bit is set to 1 and 
                            the command-queue stalls until this bit is cleared. 
                            When `cqmf` is set to 1, an interrupt is generated 
                            if an interrupt is not already pending 
                            (i.e., `ipsr.cip == 1`) and not masked 
                            (i.e. `cqsr.cie == 0`). To re-enable command 
                            processing, software should clear this bit by 
                            writing 1. 
|9    |`cmd_to`|RW1C      | If the execution of a command leads to a 
                            timeout (e.g. a command to invalidate device ATC 
                            may timeout waiting for a completion), then the 
                            command-queue sets the `cmd_to` bit and stops 
                            processing from the command-queue. When `cmd_to` is
                            set to 1 an interrupt is generated if an interrupt 
                            is not already pending (i.e., `ipsr.cip == 1`) and 
                            not masked (i.e. `cqsr.cie == 0`). To re-enable 
                            command processing software should clear this bit 
                            by writing 1. 
|10   |`cmd_ill`|RW1C     | If an illegal or unsupported command is fetched and
                            decoded by the command-queue then the command-queue 
                            sets the `cmd_ill` bit and stops processing from the
                            command-queue. When `cmd_ill` is set to 1, 
                            an interrupt is generated if not already pending 
                            (i.e. `ipsr.cip == 1`) and not masked 
                            (i.e.  `cqsr.cie == 0`). To re-enable command 
                            processing software should clear this bit by 
                            writing 1. 
|11   |`fence_w_ip`|RW1C  | An IOMMU that supports only wired interrupts sets 
                            `fence_w_ip` bit is set to indicate completion of a 
                            `IOFENCE.C` command. An interrupt on setting 
                            `fence_w_ip` if not already pending 
                            (i.e. `ipsr.cip == 1`) and not masked 
                            (i.e. `cqsr.cie == 0`) and `fence_w_ip` is 0. 
                            To re-enable interrupts on `IOFENCE.C` completion
                            software should clear this bit by writing 1.
                            This bit is reserved if the IOMMU uses MSI. 
|15:12|`WPRI`   |WPRI     | Reserved for standard use
|16   |`cqon`   |RO       | The command-queue is active if `cqon` is 1.
                            IOMMU behavior on changing cqb when busy is 1 or 
                            `cqon` is 1 is implementation defined. The software 
                            recommended sequence to change `cqb` is to first 
                            disable the command-queue by clearing cqen and 
                            waiting for both `busy` and `cqon` to be 0 before 
                            changing the `cqb`.
|17   |`busy`   |RO       | A write to `cqcsr` may require the IOMMU to perform
                            many operations that may not occur synchronously 
                            to the write. When a write is observed by the 
                            `cqcsr`, the `busy` bit is set to 1.

                            When the `busy` bit is 1, behavior of additional 
                            writes to the `cqcsr` is implementation defined. 
                            Some implementations may ignore the second write and
                            others may perform the actions determined by the 
                            second write.

                            Software must verify that the busy bit is 0 before 
                            writing to the `cqcsr`. An IOMMU that can complete 
                            controls synchronously may hard-wire this bit to 0.

                            An IOMMU that can complete these operations 
                            synchronously may hard-wire this bit to 0.
|27:18 |`WPRI`|WPRI      | Reserved for standard use
|31:28 |_custom_|        | _These bits are reserved for custom use._
|===
[NOTE]
====
Command-queue being empty does not imply that all commands fetched from the 
command-queue have been completed. When the command-queue is requested to be 
disabled, an implementation may either complete the already fetched commands 
or abort execution of those commands. Software must use an `IOFENCE.C` command 
to wait for all previous commands to be committed, if so desired, before 
turning off the command-queue.
====

[[FQCSR]]
=== Fault queue CSR (`fqcsr`)

This 32-bits register (RW) is used to control the operations and report the
status of the fault-queue.

.Fault queue CSR register fields

[wavedrom, , ]
....
{reg: [
  {bits: 1, name: 'fqen'},
  {bits: 1, name: 'fie'},
  {bits: 6, name: 'WPRI'},
  {bits: 1, name: 'fqmf'},
  {bits: 1, name: 'fqof'},
  {bits: 6, name: 'WPRI'},
  {bits: 1, name: 'fqon'},
  {bits: 1, name: 'busy'},
  {bits: 10, name: 'WPRI'},
  {bits: 4, name: 'Custom use'},
], config:{lanes: 4, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits  |Field |Attribute | Description
|0     |`fqen`|RW        | The fault-queue enable bit enables the fault-queue 
                           when set to 1. 
                           Changing `fqen`  from 0 to 1, resets the `fqh` and 
                           `fqt` to 0 and clears `fqcsr` bits `fqmf` and `fqof`.
                           The fault-queue may take some time to be active
                           following setting the `fqen` to 1. When the fault 
                           queue is active, the `fqon` bit reads 1.  

                           When `fqen` is changed from 1 to 0, the fault-queue 
                           may stay active till in-flight fault-recording is 
                           completed. When the fault-queue is off, the `fqon` 
                           bit reads 0. The IOMMU guarantees that there are no 
                           in-flight implicit writes to the fault-queue in 
                           progress when `fqon` reads 0 and no new fault 
                           records will be written to the fault-queue. 
|1     |`fie` |RW        | Fault queue interrupt enable bit enables generation 
                           of interrupts from fault-queue when set to 1.
|7:2   |`WPRI`|WPRI      | Reserved for standard use
|8     |`fqmf`|RW1C      | The `fqmf` bit is set to 1 if the IOMMU encounters 
                           an access fault when storing a fault record to the 
                           fault queue. The fault-record that was attempted to 
                           be written is discarded and no more fault records 
                           are generated until software clears `fqmf` bit by 
                           writing 1 to the bit. An interrupt is generated if 
                           enabled and not already pending 
                           (i.e. `ipsr.fip == 1`) and not masked 
                           (i.e. `fqsr.fie == 0`).
|9     |`fqof`|RW1C      | The fault-queue-overflow bit is set to 1 if the 
                            IOMMU needs to queue a fault record but the 
                            fault-queue is full (i.e., `fqh == fqt - 1`) 

                            The fault-record is discarded and no more fault 
                            records are generated till software clears `fqof` 
                            by writing 1 to the bit. An interrupt is generated 
                            if not already pending (i.e. `ipsr.fip == 1`) and 
                            not masked (i.e. `fqsr.fie == 0`).
|10:15 |`WPRI`|WPRI      | Reserved for standard use
|16    |`fqon`|RO        | The fault-queue is active if `fqon` reads 1.
                           IOMMU behavior on changing `fqb` when `busy` is 1 
                           or `pqon` is 1 implementation defined. The 
                           recommended sequence to change `fqb` is to first 
                           disable the fault-queue by clearing `fqen` and 
                           waiting for both `busy` and `fqon` to be 0 before 
                           changing `fqb`.
|17    |`busy`|RO        | Write to `fqcsr` may require the IOMMU to perform 
                           many operations that may not occur synchronously to 
                           the write.
                           When a write is observed by the fqcsr, the `busy` 
                           bit is set to 1. When the `busy` bit is 1, behavior 
                           of additional writes to the `fqcsr` are 
                           implementation defined. Some implementations may 
                           ignore the second write and others may perform the 
                           actions determined by the second write.

                           Software should ensure that the `busy` bit is 0 
                           before writing to the `fqcsr`. 

                           An IOMMU that can complete controls synchronously 
                           may hard-wire this bit to 0. 
|27:18 |`WPRI`|WPRI      | Reserved for standard use
|31:28 |_custom_|        | _These bits are reserved for custom use._
|===

[[PQCSR]]
=== Page-request-queue CSR (`pqcsr`)

This 32-bits register (RW) is used to control the operations and report the
status of the page-request-queue.

.Page-request-queue CSR register fields

[wavedrom, , ]
....
{reg: [
  {bits: 1, name: 'pqen'},
  {bits: 1, name: 'pie'},
  {bits: 6, name: 'WPRI'},
  {bits: 1, name: 'pqmf'},
  {bits: 1, name: 'pqof'},
  {bits: 6, name: 'WPRI'},
  {bits: 1, name: 'pqon'},
  {bits: 1, name: 'busy'},
  {bits: 10, name: 'WPRI'},
  {bits: 4, name: 'Custom use'},
], config:{lanes: 4, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field   |Attribute | Description
|16     |`pqon`  |RW        | The page-request-enable bit enables the
                              page-request-queue when set to 1. 

                              Changing `pqen` from 0 to 1, resets the `pqh` 
                              and `pqt` to 0 and clears `pqcsr` bits `pqmf` and
                              `pqof` to 0. The page-request-queue may take 
                              some time to be active following setting the 
                              `pqen` to 1. When the page-request-queue is 
                              active, the `pqon` bit reads 1.

                              When `pqen` is changed from 1 to 0, the 
                              page-request-queue may stay active till in-flight 
                              page-request writes are completed. When the
                              page-request-queue turns off, the `pqon` bit 
                              reads 0.

                              When `pqon` reads 0, the IOMMU guarantees that 
                              there are no older in-flight implicit writes to 
                              the queue memory and no further implicit writes 
                              will be generated to the queue memory. 

                              The IOMMU may respond to “Page Request” messages 
                              received when page-request-queue is off or in 
                              the process of being turned off, as having 
                              encountered a catastrophic error as defined by 
                              the PCIe ATS specifications
|1      |`pie`   |RW        | The page-request-queue-interrupt-enable (`pie`) 
                              bit when set to 1, enables generation of 
                              interrupts from page-request-queue.
|7:2    |`WPRI`  |WPRI      | Reserved for standard use
|8      |`pqmf`  |RW1C      | The `pqmf` bit is set to 1 if the IOMMU 
                              encounters an access fault when storing a 
                              page-request message to the page-request-queue.

                              When `pqmf` is set to 1, an interrupt is 
                              generated if not already pending 
                              (i.e. `ipsr.pip == 1`) and not masked 
                              (i.e. `pqsr.pie == 1`).

                              The "Page Request" message that caused the `pqmf` 
                              or `pqof` error and all subsequent page-request 
                              messages are discarded till software clears the 
                              `pqof` and/or `pqmf` bits by writing 1 to it. 

                              The IOMMU may respond to “Page Request” messages 
                              that caused the `pqof` or `pqmf` bit to be set 
                              and all subsequent “Page Request” messages 
                              received while these bits are 1 as having 
                              encountered a catastrophic error as defined by 
                              the PCIe ATS specifications
|9      |`pqof`   |RW1C     | The page-request-queue-overflow bit is set to 1 
                              if the page-request queue overflows i.e. IOMMU 
                              needs to queue a page-request message but the 
                              page-request queue is full 
                              (i.e., `pqh == pqt - 1`). 

                              When `pqof` is set to 1, an interrupt is 
                              generated if not already pending 
                              (i.e. `ipsr.pip == 1`) and not masked 
                              (i.e. `pqsr.pie == 1`).

                              The "Page Request" message that caused the `pqmf` 
                              or `pqof` error and all subsequent page-request 
                              messages are discarded till software clears the 
                              `pqof` and/or `pqmf` bits by writing 1 to it. 

                              The IOMMU may respond to “Page Request” messages 
                              that caused the `pqof` or `pqmf` bit to be set 
                              and all subsequent “Page Request” messages 
                              received while these bits are 1 as having 
                              encountered a catastrophic error as defined by 
                              the PCIe ATS specifications
|15:10  |`WPRI`   |WPRI     | Reserved for standard use
|16     |`pqon`   |RO       | The page-request is active when `pqon` reads 1.

                              IOMMU behavior on changing `pqb` when `busy` is 1
                              or `pqon` is 1 implementation defined. The 
                              recommended sequence to change `pqb` is to first 
                              disable the page-request queue by clearing `pqen`
                              and waiting for both `busy` and `pqon` to be 0 
                              before changing `pqb`.
|17     |`busy`   |RO       | A write to `pqcsr` may require the IOMMU to 
                              perform many operations that may not occur 
                              synchronously to the write. When a write is 
                              observed by the `pqcsr`, the `busy` bit is set 
                              to 1.

                              When the `busy` bit is 1, behavior of additional 
                              writes to the `pqcsr` are implementation defined.
                              Some implementations may ignore the second write 
                              and others may perform the actions determined by 
                              the second write. Software should ensure that the
                              `busy` bit is 0 before writing to the `pqcsr`.

                              An IOMMU that can complete controls synchronously
                              may hard-wire this bit to 0
|27:18 |`WPRI`   |WPRI      | Reserved for standard use
|31:28 |_custom_ |          | _These bits are designated for custom use._
|===

[[IPSR]]
=== Interrupt pending status register (`ipsr`)
This 32-bits register (RW1C) reports the pending interrupts which require 
software service. Each interrupt-pending bit in the register corresponds to 
a interrupt source in the IOMMU. When an interrupt-pending bit in the register
is set to 1 the IOMMU will not signal another interrupt from that source till
software clears that interrupt-pending bit by writing 1 to clear it.

.Interrupt pending status register fields

[wavedrom, , ]
....
{reg: [
  {bits: 1, name: 'cip'},
  {bits: 1, name: 'fip'},
  {bits: 1, name: 'pmip'},
  {bits: 1, name: 'pip'},
  {bits: 4, name: 'WPRI'},
  {bits: 8, name: 'Custom use'},
  {bits: 16, name: 'WPRI'},
], config:{lanes: 2, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field   |Attribute | Description
|0      |`cip`   |RW1C      | The command-queue-interrupt-pending
|1      |`fip`   |RW1C      | The fault-queue-interrupt-pending
|2      | `pmip` |RW1C      | The performance-monitoring-interrupt-pending
|3      | `pip`  |RW1C      | The page-request-queue-interrupt-pending
|7:4    |`WPRI`  |WPRI      | Reserved for standard use
|15:8   |_custom_|          | _These bits are designated for custom use._
|31:16  |`WPRI`  |WPRI      | Reserved for standard use
|===

[[OVF]]
=== Performance-monitoring counter overflow status (`iocountovf`)
The performance-monitoring counter overflow status is a 32-bit read-only
register that contains shadow copies of the OF bits in the `iohpmevt*`
registers - where `iocntovf` bit X corresponds to `iohpmevtX` and bit 0 corresponds
to the OF bit of `iohpmcycles`.

This register enables overflow interrupt handler software to quickly and easily
determine which counter(s) have overflowed.

.iocntovf register fields

[wavedrom, , ]
....
{reg: [
  {bits:  1, name: 'CY'},
  {bits: 31, name: 'HPM'},
], config:{lanes: 1, hspace:1024}}
....


[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field   |Attribute | Description
|0      |`CY`    |RO        | Shadow of `iohpmcycles.OF`
|31:1   |`HPM`   |RO        | Shadow of `iohpmevt*.OF`
|===

[[INH]]
=== Performance-monitoring counter inhibits (`iocountinh`)
The performance-monitoring counter inhibits is a 32-bits WARL register where
that contains bits to inhibit the corresponding counters from counting. Bit X
when set inhibits counting in `iohpmctrX` and bit 0 inhibits counting in
`iohpmcycles`.

.iocntinh register fields

[wavedrom, , ]
....
{reg: [
  {bits:  1, name: 'CY'},
  {bits: 31, name: 'HPM'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field   |Attribute | Description
|0      |`CY`    |RW        | When set, `iohpmcycles` counter is inhibited 
                              from counting.
|31:1   |`HPM`   |WARL      | When bit X is set, then counting of events in
                              `iohpmctrX` is inhibited.
|===

[NOTE]
====
When the `iohpmcycles` counter is not needed, it is desirable to conditionally
inhibit it to reduce energy consumption. Providing a single register to 
inhibit all counters allows a) one or more counters to be atomically programmed
with events to count b) one or more counters to be sampled atomically.
====

[[CYC]]
=== Performance-monitoring cycles counter (`iohpmcycles`)
This 64-bits register is a free running clock cycle counter.
There is no associated `iohpmevt0`.

.iohpmcycles register fields

[wavedrom, , ]
....
{reg: [
  {bits: 63, name: 'counter'},
  {bits: 1, name: 'OF'},
], config:{lanes: 2, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field    |Attribute | Description
|62:0   |`counter`|WARL      | Cycles counter value.
|63     |`OF`     |RW        | Overflow
|===

When `capabilities.HPM` is set, the `iohpmcycles` register must be present and
be at least a 32-bits wide.

[[CTR]]
=== Performance-monitoring event counters (`iohpmctr1-31`)
These registers are 64-bit WARL counter registers.

.iohpmctr* register fields

[wavedrom, , ]
....
{reg: [
  {bits: 64, name: 'counter'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field    |Attribute | Description
|63:0   |`counter`|WARL      | Event counter value.
|===

When `capabilities.HPM` is set, the `iohpmctr1-7` registers must be present 
and be at least 32-bits wide.


[[EVT]]
=== Performance-monitoring event selector (`iohpmevt1-31`)
These performance-monitoring event registers are 64-bit RW registers. When a
transaction processed by the IOMMU causes an event that is programmed to count
in a counter then the counter is incremented. In addition to matching events
the event selector may be programmed with additional filters based on
`device_id`, `process_id`, `GSCID`, and `PSCID` such that the counter is 
incremented conditionally based on the transaction matching these additional
filters. When such `device_id` based filtering is used, the match may be 
configured to be a precise match or a partial match. A partial match allows
a transactions with a range of IDs to be counted by the counter.

.iohpmevt* register fields

[wavedrom, , ]
....
{reg: [
  {bits: 15, name: 'eventID'},
  {bits: 1, name: 'DMASK'},
  {bits: 20, name: 'PID_PSCID'},
  {bits: 24, name: 'DID_GSCID'},
  {bits: 1, name: 'PV_PSCV'},
  {bits: 1, name: 'DV_GSCV'},
  {bits: 1, name: 'IDT'},
  {bits: 1, name: 'OF'},
], config:{lanes: 8, hspace:1024}}
....

[width=100%]
[%header, cols="^1,2,^1,5"]
|===
|Bits   |Field      |Attribute | Description
|14:0   |`eventID`  |WARL     a| Indicates the event to count. A value of 0 
                                 indicates no events are counted. +
                                 Encodings 1 to 16383 are reserved for standard
                                 events defined in the <<Event_list>>. +
                                 Encodings 16384 to 32767 are for reserved for 
                                 custom use and are implementation defined. +
                                 When `eventID` is changed, including to 0, 
                                 the counter retains its value.
|15     |`DMASK`    |WARL      | When set to 1, partial matching of the
                                 `DID_GSCID` is performed for the transaction.
                                 The lower bits of the `DID_GSCID` all the way 
                                 to the first low order 0 bit (including
                                 the 0 bit position itself) are masked.
|35:16  |`PID_PSCID`|WARL      | `process_id` if `IDT` is 0, 
                                 `PSCID` if `IDT` is 1
| 59:36 |`DID_GSCID`|WARL      | `device_id` if `IDT` is 0, 
                                 `GSCID` if `IDT` is 1.
| 60    |`PV_PSCV`  |WARL      | If set, only transactions with matching
                                 `process_id` or `PSCID` (based on the Filter 
                                 ID Type) are counted.
| 61    |`DV_GSCV`  |WARL      | If set, only transactions with matching
                                 `device_id` or `GSCID` (based on the Filter ID
                                 Type) are counted.
| 62    |`IDT`      |WARL      | Filter ID Type: This field indicates the type 
                                 of ID to filter on. When 0, the `DID_GSCID`
                                 field holds a `device_id` and the `PID_PSCID` 
                                 field holds a `process_id`. When 1, the
                                 `DID_GSCID` field holds a `GSCID` and
                                 `PID_PSCID` field holds a `PSCID`.
| 63    |`OF`       |WARL      | Overflow status or Interrupt disable 
|===

When `capabilities.HPM` is set, the `iohpmevt1-7` registers must be present.

The table below summarizes the filtering option for events that support 
filtering by IDs.

.filtering options
[cols="^1,1,1,5", options="header"]
|===
| *`IDT`* | *`DV_GSCV`* | *`PV_PSCV`* | *Operation*
| 0/1     | 0           | 0           | Counter increments. No ID based
                                        filtering.
| 0       |  0          | 1           | If the transaction has a valid
                                        `process_id`, counter increments if
                                        process_id matches `PID_PSCID`.
| 0       |  1          | 0           | Counter incremented if `device_id`
                                        matches `DID_GSCID`.
| 0       |  1          | 1           | If the transaction does not have a
                                        valid `process_id`, counter increments
                                        if `device_id` matches `DID_GSCID`.
                                        If the transaction has a valid
                                        `process_id`, counter increments if
                                        `device_id` matches `DID_GSCID` and
                                        `process_id` matches `PID_PSCID`.
| 1       |  0          | 1           | If the transaction has a valid
                                        `process_id`, counter increments if 
                                        the `PSCID` of that process matches
                                        `PID_PSCID`.
| 1       |  1          | 0           | Counter incremented if `GSCID` of the
                                        device matches `DID_GSCID`.
| 1       |  1          | 1           | If the transaction does not have a
                                        valid `process_id`, counter increments
                                        if `GSCID` of the device matches
                                        `DID_GSCID`.
                                        If the transaction has a valid
                                        `process_id`, counter increments if
                                        `GSCID` of the device matches
                                        `DID_GSCID` and `PSCID` of the process
                                         matches `PID_PSCID`.
|===

When filtering by `device_id` or `GSCID` is selected and the event supports
ID based filtering, the DMASK field can be used to configure a partial match.
When DMASK is set to 1, partial matching of the `DID_GSCID` is performed for
the transaction. The lower bits of the `DID_GSCID` all the way to the first 
low order 0 bit (including the 0 bit position itself) are masked.

The following example illustrates the use of DMASK and filtering by `device_id`.

.DMASK with IDT set to `device_id` based filtering
[cols="^1,3,3", options="header"]
|===
| *DMASK* | *DID_GSCID*                  | *Comment*
| 0       | yyyyyyyy  yyyyyyyy  yyyyyyyy | One specific seg:bus:dev:func
| 1       | yyyyyyyy  yyyyyyyy  yyyyy011 | seg:bus:dev - any func
| 1       | yyyyyyyy  yyyyyyyy  01111111 | seg:bus - any dev:func
| 1       | yyyyyyyy  01111111  11111111 | seg - any bus:dev:func
|===

The following table lists the standard events that can be counted:

[[Event_list]]
.Standard Events list
[cols="^1,3,^3", options="header"]
|===
| *eventID*  | *Event counted*              | *IDT settings supported*
| 0          | Do not count                 | 
| 1          | Untranslated requests        | 0
| 2          | Translated requests          | 0
| 3          | ATS Translation requests     | 0
| 4          | Device-context cache miss    | 0 
| 5          | Process-context cache miss   | 0
| 6          | TLB miss                     | 0/1
| 7          | Device Directory Walks       | 0 
| 8          | Process Directory Walks      | 0
| 9          | S/VS-stage Page Table Walks  | 0/1
| 10         | G-stage Page Table Walks     | 0/1
| 11 - 16383 | reserved for future standard | -
|===

Some events types may be filtered by IDs. When a event type that does not 
support filtering by IDs is programmed then the associated counter does not
increment.

The `OF` bit is set when the corresponding `iohpmctr*` overflows, and remains
set until cleared by software. Since `iohpmctr*` values are unsigned values,
overflow is defined as unsigned overflow. Note that there is no loss of
information after an overflow since the counter wraps around and keeps 
counting while the sticky `OF` bit remains set.

If an `iohpmctr*` overflows while the associated `OF` bit is zero, then a HPM
Counter Overflow interrupt is generated. If the `OF` bit is one, then no
interrupt request is generated. Consequently the `OF` bit also functions as a
count overflow interrupt disable for the associated `iohpmctr*`.

A pending HPM Counter Overflow interrupt (OR of all `iohpmctr*` overflows) is 
and reported through `ipsr` register.

[NOTE]
====
There are not separate overflow status and overflow interrupt enable bits. In
practice, enabling overflow interrupt generation (by clearing the `OF` bit) is
done in conjunction with initializing the counter to a starting value. Once a
counter has overflowed, it and the `OF` bit must be reinitialized before
another overflow interrupt can be generated.
====

//[[CONF]]
//=== Counters reserved for confidential mode usage (`iocntconf`)

//Reserved for future standard use.

[[ICVEC]]
=== Interrupt-cause-to-vector register (`icvec`)

Interrupt-cause-to-vector register maps a cause to a vector.  All causes can 
be mapped to same vector or a cause can be given a unique vector. 

The vector is used:

. By a MSI capable IOMMU to index into MSI configuration table (`msi_cfg_tbl`)
  to determine the MSI to generate. A IOMMU is capable of generating IOMMU
  generated interrupt as a MSI if `capabilities.IGS==MSI` or if 
  `capabilities.IGS==BOTH` and `fctrl.WIS` is set to 1.
. By a non-MSI capable IOMMU determine the wire to use to signal the interrupt

If an implementation only supports a single vector then all bits of this
register may be hardwired to 0 (WARL). Likewise if only two vectors are 
supported then only bit 0 for each cause could be writable.

.icvec register fields

[wavedrom, , ]
....
{reg: [
  {bits: 4, name: 'civ'},
  {bits: 4, name: 'fiv'},
  {bits: 4, name: 'pmiv'},
  {bits: 4, name: 'piv'},
  {bits: 16, name: 'WPRI'},
  {bits: 32, name: 'Custom'},
], config:{lanes: 4, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field    |Attribute | Description
| 3:0   |`civ`    |WARL      | The command-queue-interrupt-vector (`civ`) 
                               is the vector number assigned to the 
                               command-queue-interrupt. 
| 7:4   |`fiv`    |WARL      | The fault-queue-interrupt-vector (`fiv`) is the
                               vector number assigned to the 
                               fault-queue-interrupt.
| 11:8  |`pmiv`   |WARL      | The performance-monitoring-interrupt-vector
                               (`pmiv`) is the vector number assigned to the
                               performance-monitoring-interrupt. 
| 15:12 |`piv`    |WARL      | The page-request-queue-interrupt-vector (`piv`)
                               is the vector number assigned to the
                               page-request-queue-interrupt.
| 31:16 |`WPRI`   |WPRI      | Reserved for standard use
| 63:32 |_custom_ |WARL      | _Reserved for custom use_
|===

[[MSI]]
=== MSI configuration table (`msi_cfg_tbl`)
IOMMU that supports MSI implements a MSI configuration table that is indexed 
by the vector from `icvec` to determine a MSI table entry. Each MSI table 
entry for interrupt vector `x` has three registers `msi_addr_x`, `msi_data_x`, 
and `msi_vec_ctrl_x`. These registers are hard wired to 0 if the IOMMU does 
not support MSI.

.MSI configuration table structure
[width=100%]
[%header, cols="10,10,3"]
|===
|bit 63                 >s|                   bit 0|Byte Offset
2+^|Entry 0: Message address                       |+000h      
^|Entry 0: Vector Control  ^|Entry 0: Message Data |+008h      
2+^|Entry 1: Message address                       |+010h      
^|Entry 1: Vector Control  ^|Entry 1: Message Data |+018h      
2+^|...                                            |+020h     
|===

.`msi_addr_x` register fields
[wavedrom, , ]
....
{reg: [
  {bits: 2, name: '0'},
  {bits: 54, name: 'ADDR'},
  {bits: 8, name: 'WPRI'},
], config:{lanes: 2, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field |Attribute |Description
|1:0    | 0    |RO     |Fixed to 0
|55:2   |`ADDR`|WARL   |Holds the 4-byte aligned MSI address.
|63:56  |`WPRI`|WPRI   | Reserved for future use.
|===


.`msi_data_x` register fields
[wavedrom, , ]
....
{reg: [
  {bits: 32, name: 'data'},
], config:{lanes: 1, hspace:1024}}
....

[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field |Attribute |Description
|31:0   |`data`| RW       | Holds the 4-byte MSI data
|===


.`msi_vec_ctrl_x` register fields
[wavedrom, , ]
....
{reg: [
  {bits: 1, name: 'M'},
  {bits: 31, name: 'WPRI'},
], config:{lanes: 1, hspace:1024}}
....
[width=100%]
[%header, cols="^1,1,^1,6"]
|===
|Bits   |Field |Attribute | Description
|0      |`M`   |RW        | When the mask bit `M` is 1, the corresponding 
                            interrupt vector is masked and the IOMMU is 
                            prohibited from sending the associated message.
|31:1   |`WPRI`|WPRI      | Reserved for future use.
|===
