== In-memory queue interface
Software and IOMMU interact using 3 in-memory queue data structures.

* A command-queue (`CQ`) used by software to queue commands to the IOMMU.

* A fault/event queue (`FQ`) used by IOMMU to bring faults and events to 
  software attention.

* A page-request queue (`PQ`) used by IOMMU to report “Page Request” messages 
  received from PCIe devices. This queue is supported if the IOMMU supports 
  PCIe defined Page Request Interface.

.IOMMU in-memory queues
["ditaa",shadows=false, separation=false, font=courier, fontsize: 16]
....
            +---+---+--------------------------------+---+----+
  +-------->|.. | . |       Command Queue            | . | .. |
  |         +---+---+--------------------------------+---+----+
  |           ^                                        ^
+-+-+         |                                        |
|CQB|         |                                        |
+---+         |                                        |
|CQH+---------+                                        |
+---+                                                  |
|CQT+--------------------------------------------------+
+---+       +---+---+--------------------------------+---+----+
  +-------->|.. | . |       Fault Queue              | . | .. |
  |         +---+---+--------------------------------+---+----+
  |           ^                                        ^
+-+-+         |                                        |
|FQB|         |                                        |
+---+         |                                        |
|FQH+---------+                                        |
+---+                                                  |
|FQT+--------------------------------------------------+
+---+       +---+---+--------------------------------+---+----+
  +-------->|.. | . |       Page Request Queue       | . | .. |
  |         +---+---+--------------------------------+---+----+
  |           ^                                        ^
+-+-+         |                                        |
|PQB|         |                                        |
+---+         |                                        |
|PQH+---------+                                        |
+---+                                                  |
|PQT+--------------------------------------------------+
+---+
....
Each queue is a circular buffer with a head controlled by the consumer of data
from the queue and a tail controlled by the producer of data into the queue.
IOMMU is the producer of records into `PQ` and `FQ` and controls the tail register.
IOMMU is the consumer of commands produced by software into the CQ and controls
the head register. The tail register holds the index into the queue where the
next entry will be written by the producer. The head register holds the index 
into the queue where the consumer will read the next entry to process.

A queue is empty if the head is equal to the tail. A queue is full if the tail
is one minus the head. The head and tail wrap around when they reach the end of
the circular buffer.

The producer of data must ensure that the data written to queue and the
tail update are ordered such that the consumer that observes an update to the 
tail register must also observe all data produced into the queue between the
offsets determined by the head and the tail. 

[NOTE]
====
All RISC-V IOMMU implementations are required to support in-memory queues 
located in main memory. Supporting in-memory queues in I/O memory is not required
but is not prohibited by this specification.
====


=== Command-Queue (CQ)

Command queue is used by software to queue commands to be processed by the 
IOMMU.

The PPN of the base of this in-memory queue and the size of the queue is 
configured into a memory-mapped register called command-queue base (`cqb`).

The tail of the command-queue resides in a software controlled read/write 
memory-mapped register called command-queue tail (`cqt`). The `cqt` is an 
index into the next command queue entry that software will write. Subsequent 
to writing the command(s), software advances the `cqt` by the count of the 
number of commands written. 

The head of the command-queue resides in a read-only memory-mapped IOMMU 
controlled register called command-queue head (`cqh`). The `cqh` is an index 
into the command queue that IOMMU should process next. Subsequent to reading
each command the IOMMU advances the `cqh` by 1. If `cqh` == `cqt`, the 
command-queue is empty. If `cqt` == (`cqh` - 1) the command-queue is full.

IOMMU commands are grouped into a major command group determined by the `opcode`
and within each group the `func3` field specifies the function invoked by that 
command. The `opcode` defines the format of the operand fields. One or more of
those fields may be used by the specific function invoked.

.Format of an IOMMU command

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode'},
  {bits: 3, name: 'func3'},
  {bits: 118, name: 'operands'},
], config:{lanes: 2, hspace:1024, fontsize: 16}}
....

==== IOMMU Page-Table cache invalidation commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IOTINVAL(0x1)'},
  {bits: 3, name: 'func3',  attr: ['VMA-0x0', 'GVMA-0x1']},
  {bits: 1, name: 'PSCV'},
  {bits: 1, name: 'AV'},
  {bits: 1, name: 'GV'},
  {bits: 3, name: 'rsvd'},
  {bits: 20, name: 'PSCID'},
  {bits: 4, name: 'rsvd'},
  {bits: 16, name: 'GSCID'},
  {bits: 8, name: 'rsvd'},
  {bits: 52, name: 'ADDR[63:12]'},
  {bits: 12, name: 'rsvd'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

IOMMU operations cause implicit reads to PDT, first-stage and second-stage page
tables. To reduce latency of such reads, the IOMMU may cache entries from the 
first and/or second-stage page tables in the IOMMU-address-translation-cache 
(IOATC). These caches may not observe modifications performed by software to 
these data structures in memory.

The IOMMU translation-table cache invalidation commands, IOTINVAL.VMA and 
IOTINVAL.GVMA synchronize updates to in-memory S/VS-stage and G-stage 
page table data structures with the operation of the IOMMU and flush the 
matching IOATC entries.

The `GV` operand indicates if the Guest-Soft-Context ID (`GSCID`) operand is 
valid. The `PSCV` operand indicates if the Process Soft-Context ID (`PSCID`) 
operand is valid. Setting `PSCV` to 1 is allowed only for `IOTINVAL.VMA`. The 
`AV` operand indicates if the address (`ADDR`) operand is valid. When `GV` is 0,
 the translations associated with the host (i.e. those where the second-stage 
translation is not active) are operated on.

`IOTINVAL.VMA` ensures that previous stores made to the first-stage page 
tables by the harts are observed by the IOMMU before all subsequent implicit 
reads from IOMMU to the corresponding first-stage page tables.

[[IVMA]]

.`IOTINVAL.VMA` operands and operations
[width=75%]
[%header, cols="3,3,3,20"]
|===
|`GV`|`AV`|`PSCV`| Operation
|0   |0   |0     | Invalidates cached information from any level of 
                   the S-stage page table, for all host address spaces.
|0   |0   |1     | Invalidates cached information from any level of the S-stage
                   page tables, but only for the host address space identified 
                   by `PSCID` operand. Accesses to global mappings are not 
                   ordered. 
|0   |1   |0     | Invalidates cached information from leaf 
                   S-stage page table entries corresponding to the IOVA in 
                   `ADDR`, for all host address spaces.
|0   |1   |1     | Invalidates cached information from leaf 
                   S-stage page table entries corresponding to the IOVA in 
                   `ADDR`, for the host address space identified by `PSCID` 
                   operand.
                   Global mappings may not be invalidated.
|1   |0   |0     | Invalidates cached information from any level of 
                   the VS-stage page table, for all VM address spaces 
                   associated with `GSCID`.
|1   |0   |1     | Invalidates cached information from any level of
                   the VS-stage page tables, but only for the VM address 
                   space identified by `PSCID` and `GSCID` operand. Accesses to 
                   global mappings are not ordered.
|1   |1   |0     | Invalidates cached information from  leaf 
                   VS-stage page table entries corresponding to the IOVA in 
                   `ADDR`, for all VM address spaces associated with the `GSCID` 
                   operand.
|1   |1   |1     | Invalidates cached information from leaf 
                   VS-stage page table entries corresponding to the IOVA in 
                   `ADDR`, for the VM address space identified by `PSCID` and 
                   `GSCID` operand. Global mappings may not be invalidated.
|===

`IOTINVAL.GVMA` ensures that previous stores made to the G-stage page 
tables are observed before all subsequent implicit reads from IOMMU to the 
corresponding G-stage page tables. Setting `PSCV` to 1 with IOTINVAL.GVMA
is illegal.

[[IGVMA]]

.`IOTINVAL.GVMA` operands and operations
[width=75%]
[%header, cols="3,3,20"]
|===
| `GV` | `AV`   | Operation
| 0    | n/a    | Invalidates cached information from any level of the 
                  G-stage page table, for all VM address spaces.
| 1    | 0      | Invalidates cached information from any level of the 
                  G-stage page tables, but only for all VM address spaces
                  identified by the `GSCID` operand.
| 1    | 1      | Invalidates cached information from leaf G-stage page 
                  table entries corresponding to the guest-physical-address in
                  `ADDR` operand, for the all VM address spaces identified 
                  `GSCID` operand.
|===

[NOTE]
====
Implementations that cache VA to PA translations may ignore the 
guest-physical-address in `ADDR` operand of `IOTINVAL.GVMA`, when valid, and 
perform an invalidation of all virtual-addresses in VM address spaces 
identified by the `GSCID` operand if valid or all host address spaces if the 
`GSCID` operand is not valid.

Simpler implementations may ignore the operand of `IOTINVAL.VMA` and/or 
`IOTINVAL.GVMA` and always perform a global invalidation across all address 
spaces.
====

==== IOMMU directory cache commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IODIR(0x2)'},
  {bits: 3, name: 'func3',  attr: ['INVAL_DDT-0x0', 'INVAL_PDT-0x1']},
  {bits: 1, name: 'DV'},
  {bits: 5, name: 'rsvd'},
  {bits: 20, name: 'PID'},
  {bits: 4, name: 'rsvd'},
  {bits: 16, name: 'DID'},
  {bits: 64, name: 'rsvd'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

IOMMU operations cause implicit reads to DDT and/or PDT. To reduce latency of 
such reads, the IOMMU may cache entries from the DDT and/or PDT in IOMMU 
directory caches. These caches may not observe modifications performed by 
software to these data structures in memory.

[[IDDT]]

The IOMMU DDT cache invalidation command, `IODIR.INVAL_DDT` synchronize updates 
to DDT with the operation of the IOMMU and flushes the matching cached entries.

[[IPDT]]

The IOMMU PDT cache invalidation command, `IODIR.INVAL_PDT` synchronize updates 
to PDT with the operation of the IOMMU and flushes the matching cached entries.

The `DV` operand indicates if the device ID (`DID`) operand is valid.

`IODIR.INVAL_DDT` guarantees that any previous stores made by a RISC-V hart to 
the DDT are observed before all subsequent implicit reads from IOMMU to DDT. 
If `DV` is 0, then the command invalidates all  DDT and PDT entries cached for 
all devices. If `DV` is 1, then the command invalidates cached leaf level DDT 
entry for the device identified by `DID` operand and all associated PDT entries.
The `PID` operand is reserved for `IODIR.INVAL_DDT`.

`IODIR.INVA_PDT` guarantees that any previous stores made by a RISC-V hart to 
the PDT are observed before all subsequent implicit reads from IOMMU to PDT. 
The command invalidates cached leaf PDT entry for the specified `PID` and `DID`.

[NOTE]
====
Some pointers in the Device directory or Process Directory may be guest-physical
addresses. If G-stage page table used for these translations are modified, 
software must issue the appropriate `IODIR` command as some implementations may 
choose to cache the translated pointers in the IOMMU directory caches. 

`IOTINVAL` command has no effect on the IOMMU directory caches.
====

==== IOMMU Command-queue Fence commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IOFENCE(0x3)'},
  {bits: 3, name: 'func3',  attr: 'C-0x0'},
  {bits: 1, name: 'PR'},
  {bits: 1, name: 'PW'},
  {bits: 1, name: 'AV'},
  {bits: 1, name: 'WIS'},
  {bits: 18, name: 'rsvd'},
  {bits: 32, name: 'DATA'},
  {bits: 2, name: 'rsvd'},
  {bits: 62, name: 'ADDR'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

The IOMMU fetches commands from the CQ in order but the IOMMU may execute the 
fetched commands out of order. The IOMMU advancing `cqh` is not a guarantee 
that the commands fetched by the IOMMU have been executed or committed. 

A `IOFENCE.C` command guarantees that all previous commands fetched from the CQ 
have been completed and committed. 

The commands may be used to order memory accesses from I/O devices connected to
the IOMMU as viewed by the IOMMU, other RISC-V harts, and external devices or 
co-processors. The `PR` and `PW` bits can be used to request that the IOMMU ensure 
that all previous requests from devices that have already been processed by the
IOMMU be committed to a global ordering point such that they can be observed by
all RISC-V harts and IOMMUs in the machine. 

The wired-interrupt-signaling (`WIS`) bit when set to 1 causes a wired-interrupt
from the command queue to be generated on completion of `IOFENCE.C`. This bit is
reserved if the IOMMU supports MSI.

[NOTE]
====
Software should ensure that all previous read and writes processed by the IOMMU
have been committed to a global ordering point before reclaiming memory that was
previously made accessible to a device. A safe sequence for such memory 
reclamation is to first update the page tables to disallow access to the memory 
from the device and then use the `IOTINVAL.VMA` or `IOTINVAL.GVMA` appropriately 
to synchronize the IOMMU with the update to the page table. As part of the 
synchronization if the memory reclaimed was previously made read accessible to 
the device then request ordering of all previous reads; else if the memory 
reclaimed was previously made write accessible to the device then request 
ordering of all previous reads and writes. Ordering previous reads may be 
required if the reclaimed memory will be used to hold data that must not be made
visible to the device.

The ordering guarantees are made for accesses to main-memory. For accesses to 
I/O memory, the ordering guarantees are implementation and I/O protocol 
defined.

Simpler implementations may unconditionally order all previous memory accesses
globally.
====

The `AV` command operand indicates if `ADDR` operand and `DATA` operands are 
valid. If `AV`=1, the IOMMU writes `DATA` to memory at a 4-byte aligned address 
in `ADDR` operand as a 4-byte store. 

[NOTE]
====
Software may configure the `ADDR` command operand to specify the address of the 
`seteipnum_le`/`seteipnum_be` register in an IMSIC to cause an external 
interrupt notification on `IOFENCE.C` completion. Alternatively, software may 
program `ADDR` to a memory location and use `IOFENCE.C` to set a flag in memory
indicating command completion.
====

==== IOMMU MSI table cache invalidation  commands

This command is supported if `capabilities.MSI_FLAT` is set to 1.

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IOTINVAL(0x1)'},
  {bits: 3, name: 'func3',  attr: ['MSI-0x2']},
  {bits: 1, name: 'PSCV'},
  {bits: 1, name: 'AV'},
  {bits: 1, name: 'GV'},
  {bits: 3, name: 'rsvd'},
  {bits: 20, name: 'PSCID'},
  {bits: 4, name: 'rsvd'},
  {bits: 16, name: 'GSCID'},
  {bits: 8, name: 'rsvd'},
  {bits: 52, name: 'ADDR[63:12]'},
  {bits: 12, name: 'rsvd'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

IOMMU operations cause implicit reads to MSI page tables. To reduce latency of 
such reads, the IOMMU may cache entries from the MSI page tables.  These caches
may not observe modifications performed by software to these data structures in
memory.

`IOTINVAL.MSI` synchronizes updates to the MSI page table with the operation of 
the IOMMU and invalidates the matching cache entries.

The `PSCV` operand is reserved and must be 0 for `IOTINVAL.MSI`.

[[IMSI]]

.`IOTINVAL.MSI` operands and operations
[width=75%]
[%header, cols="3,3,20"]
|===
| `AV` | `GV`   | Operation
| 0    | 0      | Invalidates all cached MSI page table entries for host 
                  associated devices.
| 0    | 1      | Invalidates MSI page table entry identified by 
                  `INT_FILE_NUM` for host associated devices.
| 1    | 0      | Invalidates all cached MSI page table entries of VM 
                  identified by `GSCID` operand.
| 1    | 1      | Invalidates MSI page table entry identified by `INT_FILE_NUM` 
                  of VM identified by `GSCID` operand. 
|===

==== IOMMU ATS commands

This command is supported if `capabilities.ATS` is set to 1.

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'ATS(0x4)'},
  {bits: 3, name: 'func3',  attr: ['INVAL-0x0', 'PRGR-0x1']},
  {bits: 1, name: 'DSV'},
  {bits: 1, name: 'PV'},
  {bits: 4, name: 'rsvd'},
  {bits: 20, name: 'PID'},
  {bits: 4, name: 'rsvd'},
  {bits: 8, name: 'DSEG'},
  {bits: 16, name: 'RID'},
  {bits: 64, name: 'PAYLOAD'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....
The `ATS.INVAL` command instructs the IOMMU to send a “Invalidation Request” 
message to the PCIe device function identified by `RID`. An 
“Invalidation Request” message is used to clear a specific subset of the 
address range from the address translation cache in a device function. The 
`ATS.INVAL` command completes when an “Invalidation Completion” response message
is received from the device or a protocol defined timeout occurs while waiting
for a response. The IOMMU may advance the `cqh` and fetch more commands from 
CQ while a response is awaited. 

[NOTE]
====
Software that needs to know if the invalidation operation completed on the 
device may use the IOMMU command-queue fence command (`IOFENCE.C`) to wait for 
the responses to all prior “Invalidation Request” messages. The `IOFENCE.C` is 
guaranteed to not complete before all previously fetched commands were executed
and completed. A previously fetched ATS command to invalidate device ATC does 
not complete till either the request times out or a valid response is received
from the device.
====

The `ATS.PRGR` command instructs the IOMMU to send a “Page Request Group 
Response” message to the PCIe device function identified by the `RID`. The 
“Page Request Group Response” message is used by system hardware and/or 
software to communicate with the device functions page-request interface to 
signal completion of a “Page Request”, or the catastrophic failure of the 
interface.

If the `PV` operand is set to 1, the message is generated with a PASID TLP 
prefix with the PASID field set to the `PID` operand. 

The `PAYLOAD` operand of the command is used to form the message body. 

If the `DSV` operand is 1, then a valid destination segment number is specified 
by the `DSEG` operand.

[[FAULT_QUEUE]]
=== Fault/Event-Queue (`FQ`)
Fault/Event queue is an in-memory queue data structure used to report events 
and faults raised when processing transactions. Each fault record is 64 bytes.

The PPN of the base of this in-memory queue and the size of the queue is 
configured into a memory-mapped register called fault-queue base (`fqb`).

The tail of the fault-queue resides in a IOMMU controlled read-only 
memory-mapped register called `fqt`.  The `fqt` is an index into the next fault 
record that IOMMU will write in the fault-queue. Subsequent to writing the 
record, the IOMMU advances the `fqt` by 1. The head of the fault-queue resides 
in a read/write memory-mapped software controlled register called `fqh`. The `fqh`
is an index into the next fault record that SW should process next. Subsequent
to processing fault record(s) software advances the `fqh` by the count of the 
number of fault records processed. If `fqh` == `fqt`, the fault-queue is empty. If
`fqt` == (`fqh` - 1) the fault-queue is full.

.Fault-queue record
[wavedrom, , ]
....
{reg: [
  {bits: 24, name: 'DID'},
  {bits: 20, name: 'PID'},
  {bits:  1, name: 'PV'},
  {bits:  1, name: 'PRIV'},
  {bits:  6, name: 'TTYP'},
  {bits: 12, name: 'CAUSE'},
  {bits: 32, name: 'for custom use'},
  {bits: 32, name: 'reserved'},
  {bits: 64, name: 'iotval'},
  {bits: 64, name: 'iotval2'},
], config:{lanes: 8, hspace:1024, fontsize:12}}
....
The `CAUSE` is a code indicating the cause of the fault/event.

[[FAULT_CAUSE]]
.Fault record `CAUSE` field encodings
[width=75%]
[%header, cols="4,20,6"]
|===
|CAUSE | Description                         | Reported if `DTF` is 1?
|0     | Instruction address misaligned      | No
|1     | Instruction access fault            | No
|4     | Read address misaligned             | No
|5     | Read access fault                   | No
|6     | Write/AMO address misaligned        | No
|7     | Write/AMO access fault              | No
|12    | Instruction page fault              | No
|13    | Read page fault                     | No
|15    | Write/AMO page fault                | No
|20    | Instruction guest page fault        | No
|21    | Read guest-page fault               | No
|23    | Write/AMO guest-page fault          | No
|256   | All inbound transactions disallowed | Yes
|257   | DDT entry load access fault         | Yes
|258   | DDT entry not valid                 | Yes
|259   | DDT entry misconfigured             | Yes
|260   | Transaction type disallowed         | No
|261   | MSI PTE load access fault           | No
|262   | MSI PTE not valid                   | No
|263   | MSI PTE misconfigured               | No
|264   | MRIF access fault                   | No
|265   | PDT entry load access fault         | No
|266   | PDT entry not valid                 | No
|267   | PDT entry misconfigured             | No
|===

The `TTYP` field reports inbound transaction type.

.Fault record `TTYP` field encodings
[width=75%]
[%header, cols="3,20"]
|===
|TTYP   | Description
|0      | None. Fault not caused by an inbound transaction.
|1      | Untranslated read for execute transaction
|2      | Untranslated read transaction
|3      | Untranslated write/AMO transaction
|4      | Translated read for execute transaction
|5      | Translated read transaction
|6      | Translated write/AMO transaction
|7      | PCIe ATS Translation Request
|8      | Message Request
|9 - 15 | Reserved
|16 - 31| Reserved for custom use
|===

If the `TTYP` is a transaction with an IOVA then its reported in `iotval`. If 
the `TTYP` is a message request then the message code is reported in `iotval`.

`DID` holds the `device_id` of the transaction. If `PV` is 0, then `PID` and 
`PRIV` are 0. If `PV` is 1, the `PID` holds a `process_id` of the transaction 
and if the privilege of the transaction was Supervisor then `PRIV` bit is 1 
else its 0.

If the `CAUSE` is guest-page fault then the guest-physical-address right shifted
by 2 is reported in `iotval[63:2]`. If bit 0 of `iotval2` 1, then 
guest-page-fault was caused by an implicit memory access for VS-stage address 
translation. If bit 0 of `iotval2` is 1, and the implicit access was a write then
bit 1 is set to 1 else its set to 0.

The IOMMU may be unable to report faults through the fault-queue due to error 
conditions such as the fault-queue being full or the IOMMU encountering access
faults when attempting to access the queue memory. A memory-mapped fault 
control and status register (`fqcsr`) holds information about such faults. If 
the fault-queue full condition is detected the IOMMU sets a fault-queue overflow 
(`fqof`) bit in fqcsr. If the IOMMU encounters a fault in accessing the 
fault-queue memory, the IOMMU sets a fault-queue memory access fault (`fqmf`) 
bit in `fqcsr`. While either error bits are set in `fqcsr`, the IOMMU discards 
the record that led to the fault and all further fault records. When an error 
bit is in the `fqcsr` changes state from 0 to 1 or when a new fault record is
produced in the fault-queue, fault interrupt pending (`fip`) bit is set in the 
`fqcsr`. 

=== Page-Request-Queue (`PQ`)
Page-request queue is an in-memory queue data structure used to report PCIe 
ATS “Page Request” messages to software. The base PPN of this in-memory queue 
and the size of the queue is configured into a memory-mapped register called 
page-request queue base (`pqb`).

The tail of the queue resides in a IOMMU controlled read-only memory-mapped 
register called `pqt`.  The `pqt` holds an index into the queue where the next 
page-request message will be written by the IOMMU. Subsequent to writing the 
message, the IOMMU advances the `pqt` by 1. 

The head of the queue resides in a software controlled read/write memory-mapped
register called `pqh`. The `pqh` holds an index into the queue where the next 
page-request message will be received by software. Subsequent to processing the
message(s) software advances the `pqh` by the count of the number of messages 
processed.

If `pqh` == `pqt`, the page-request queue is empty. 

If `pqt` == (`pqh` - 1) the page-request queue is full.

The IOMMU may be unable to report "Page Request" messages through the queue due
to error conditions such as the queue being disabled, queue being full, or the
IOMMU encountering access faults when attempting to access queue memory. A 
memory-mapped page-request queue control and status register (`pqcsr`) is used
to hold information about such faults.  On a page queue full condition the 
page-request-queue overflow (`pqof`) bit is set in `pqcsr`. If the IOMMU 
encountered a fault in accessing the queue memory, page-request-queue memory 
access fault (`pqmf`) bit in `pqcsr`. While either error bits are set in 
`pqcsr`, the IOMMU discards all subsequent "Page Request" messages; including
the message that caused the error bits to be set. "Page request" messages that
do not require a response, i.e. those with the "Last Request in PRG" field is 0,
are silently discarded. "Page request" messages that require a response, i.e. 
those with "Last Request in PRG" field set to 1 and are not Stop Marker 
messages, may be auto-completed by an IOMMU generated 
“Page Request Group Response” message as specified by PCIe ATS specifications.

When an error bit is in the `pqcsr` changes state from 0 to 1 or when a new 
message is produced in the queue, page-request-queue interrupt pending (`pip`) 
bit is set in the `pqcsr`. 

.Page-request-queue record
[wavedrom, , ]
....
{reg: [
  {bits: 24, name: 'DID'},
  {bits: 20, name: 'PID'},
  {bits:  1, name: 'PV'},
  {bits:  1, name: 'PRIV'},
  {bits:  1, name: 'X'},
  {bits: 17, name: 'reserved'},
  {bits: 64, name: 'PAYLOAD'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

The `DID` field holds the requester ID from the message. The `PID` field is 
valid if `PV` is 1 and reports the PASID from the PASID TLP prefix of the 
message. `PRIV` is set to 0 if the message did not have a PASID TLP prefix, 
otherwise it holds the “Privilege Mode Requested” bit from the PASID TLP 
prefix. `X` bit is set to 0 if the message did not have a PASID TLP prefix, 
otherwise it reports the “Execute Requested” bit from the PASID TLP prefix. All
other fields are set to 0. The payload of the “Page Request” message 
(bytes 0x08 through 0x0F of the message) is held in the `PAYLOAD` field.


