[[hw_guidelines]]

== Hardware guidelines
This section provides guidelines to the system/hardware integrator of the 
IOMMU in the platform.

=== Integrating an IOMMU as a PCIe device
The IOMMU may be constructed as a PCIe device itself and be discoverable
as a dedicated PCIe function with PCIe defined Base Class 08h, Sub-Class 06h, 
and Programming Interface 00h.

Such IOMMU must map the IOMMU registers defined in this specification as PCIe
BAR mapped registers.

The IOMMU may support MSI or MSI-X or both. When MSI-X is supported,  the MSI-X
capability block must point to the `msi_tbl` in BAR mapped registers such that
system software can configure MSI address and data pairs for each message 
supported by the IOMMU. The MSI-X PBA may be located in the same BAR or 
another BAR of the IOMMU. The IOMMU is recommended to support MSI-X capability.

=== Faults from PMA and IOPMP
The IO bridge may invoke a PMA and/or an IOPMP checker on memory accesses from
IO devices or those generated by the IOMMU implicitly to access the in-memory
data structures. When a memory access violates a PMA check or violates an IOPMP
check, the IO bridge may abort the memory access as specified in 
<<IOBR_FAULT_RESP>>.

[[IOBR_FAULT_RESP]]
=== Aborting transactions
If the aborted transaction is an IOMMU initiated implicit memory access then the
IO bridge signals such access faults to the IOMMU itself. The details of such
signaling is implementation defined.

If the aborted transaction is a write then the IO bridge may discard the write;
the details of how the write is discarded is implementation defined. If the IO 
protocol requires a response for write transactions (e.g., AXI) then a response
as defined by the IO protocol may be generated by the IO bridge. For PCIe, for 
example, write transactions are posted and no response is returned when a write
transaction is discarded.

If the faulting transaction is a read then the device expects a completion. The
IO bridge may provide a completion to the device. The data, if returned, in such 
completion is implementation defined; usually it is a fixed value such as all 0 
or all 1. A status code may be returned to the device in the completion to 
indicate this condition. For PCIe, for example, the completion status field may 
be set to "Unsupported Request" (UR) or "Completer Abort" (CA).

=== Debug
Placeholder

=== RAS
Placeholder
