[[intro]]

== Introduction

One or two paragraphs about what a IOMMU is.
Ved
=== Glossary
<< Table >>

=== Usage models
Introduce the concept of IOVA and device_id and process_id here
Can also introduce GSCID and PSCID
==== Non-virtualized OS
DMA isolation for native OS using first stage PTs and use of PASID
Bounce buffer avoidance
Scatter/Gather
Perrine
==== Hypervisor
<< some devices may be passthrough and others retained by hypervisor>>
<< For retained devices same usage as Native OS>>
DMA isolation and passthrough of devices
MSI translation
Ved
==== Guest OS
<< Same as Native OS>> - Guest controlling first stage PT
Perrine

=== Placement and data flow
[Picture here]
Call out this is a Reference/examples
- In relation to the fabric and IO ports

- Placement of PMP
  Text talk about
  Concept of IOMMU itself being a master for implicit accesses
  There is proposed IOPMP and it sits where PMP sits
- Placement of PMA
Perrine

=== IOMMU features
list of features - call out mandatory and optional
Ved
