#!/bin/bash
GREEN='\032'
clear
echo -e "\e[0m\e[4m                                                             \e[0m"
echo -e "\e[32m\e[4m\e[1mRunning IOMMU test suite\e[0m"
test/iommu
echo -e "\e[0m\e[4m                                                             \e[0m"
cd libiommu;gcovr -s;cd ..
echo -e "\e[0m\e[4m                                                             \e[0m"
